export const ALL_PERMISSIONS = [
  'org:manage',
  'org:billing',
  'users:manage',
  'users:invite',
  'users:view',
  'products:create',
  'products:edit',
  'products:delete',
  'products:view',
  'sales:create',
  'sales:edit',
  'sales:delete',
  'sales:view',
  'customers:create',
  'customers:edit',
  'customers:delete',
  'customers:view',
  'invoices:create',
  'invoices:edit',
  'invoices:delete',
  'invoices:view',
  'expenses:create',
  'expenses:edit',
  'expenses:delete',
  'expenses:view',
  'expenses:approve',
  'purchases:create',
  'purchases:edit',
  'purchases:delete',
  'purchases:view',
  'inventory:manage',
  'inventory:view',
  'reports:view',
  'reports:export',
  'settings:manage',
  'settings:view',
] as const;

export type Permission = (typeof ALL_PERMISSIONS)[number];

export interface RoleDefinition {
  name: string;
  displayName: string;
  displayNameAr: string;
  description: string;
  descriptionAr: string;
  hierarchyLevel: number;
  permissions: Permission[];
}

export const DEFAULT_ROLES: RoleDefinition[] = [
  {
    name: 'owner',
    displayName: 'Owner',
    displayNameAr: 'المالك',
    description: 'Full access to all features, billing, and organization management',
    descriptionAr: 'وصول كامل لجميع الميزات والفواتير وإدارة المنظمة',
    hierarchyLevel: 100,
    permissions: [...ALL_PERMISSIONS],
  },
  {
    name: 'admin',
    displayName: 'Administrator',
    displayNameAr: 'مدير النظام',
    description: 'Full access except billing and organization deletion',
    descriptionAr: 'وصول كامل ما عدا الفواتير وحذف المنظمة',
    hierarchyLevel: 80,
    permissions: ALL_PERMISSIONS.filter((p) => !['org:manage', 'org:billing'].includes(p)),
  },
  {
    name: 'manager',
    displayName: 'Manager',
    displayNameAr: 'مشرف',
    description: 'Can manage day-to-day operations and team members',
    descriptionAr: 'يمكنه إدارة العمليات اليومية وأعضاء الفريق',
    hierarchyLevel: 60,
    permissions: [
      'users:invite',
      'users:view',
      'products:create',
      'products:edit',
      'products:view',
      'sales:create',
      'sales:edit',
      'sales:view',
      'customers:create',
      'customers:edit',
      'customers:view',
      'invoices:create',
      'invoices:edit',
      'invoices:view',
      'expenses:create',
      'expenses:edit',
      'expenses:view',
      'purchases:create',
      'purchases:edit',
      'purchases:view',
      'inventory:manage',
      'inventory:view',
      'reports:view',
      'settings:view',
    ],
  },
  {
    name: 'member',
    displayName: 'Member',
    displayNameAr: 'عضو',
    description: 'Can create and edit records, limited management access',
    descriptionAr: 'يمكنه إنشاء وتعديل السجلات، وصول محدود للإدارة',
    hierarchyLevel: 40,
    permissions: [
      'users:view',
      'products:create',
      'products:edit',
      'products:view',
      'sales:create',
      'sales:edit',
      'sales:view',
      'customers:create',
      'customers:edit',
      'customers:view',
      'invoices:create',
      'invoices:view',
      'expenses:create',
      'expenses:view',
      'purchases:view',
      'inventory:view',
      'reports:view',
    ],
  },
  {
    name: 'viewer',
    displayName: 'Viewer',
    displayNameAr: 'مشاهد',
    description: 'Read-only access to view data without modifications',
    descriptionAr: 'وصول للقراءة فقط لعرض البيانات بدون تعديل',
    hierarchyLevel: 20,
    permissions: [
      'products:view',
      'sales:view',
      'customers:view',
      'invoices:view',
      'expenses:view',
      'purchases:view',
      'inventory:view',
      'reports:view',
    ],
  },
];
